name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      #- name: executing remote ssh commands using ssh key
        #uses: appleboy/ssh-action@master
        #with:
          #host: ${{ secrets.SERVER_IP }}
          #username: ${{ secrets.SERVER_USERNAME }}
          #key: ${{ secrets.SSH_PRIVATE_KEY }}
          #password: ${{ secrets.SERVER_PASSWORD }}
          #script: cd /var/www/html/Fiscus_bis && git pull
      
      #  uses: easingthemes/ssh-deploy@v2.1.4
      #  env:
      #      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #      REMOTE_HOST: ${{ secrets.SERVER_IP }}
      #      REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
      #      TARGET: "/var/www/html/Fiscus_bis"

      #${{ secrets.SERVER_IP }}
      #${{ secrets.SERVER_PASSWORD }}
      #${{ secrets.SERVER_USERNAME }}
      #${{ secrets.SSH_HOST }}
      #${{ secrets.SSH_PRIVATE_KEY }}
      #${{ secrets.SSH_PRIVATE_KEY_BEGIN_END }}
      #${{ secrets.SSH_PUBLIC_KEY }}