name: CI

on: [push]

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      #  uses: easingthemes/ssh-deploy@v2.1.4
      #  env:
      #      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_BEGIN_END }}
      #      REMOTE_HOST: ${{ secrets.SERVER_IP }}
      #      REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
      #      TARGET: "/var/www/html/Fiscus_bis"

     #   - name: Install SSH Key
     #     uses: shimataro/ssh-key-action@v2
     #     with:
     #       key: ${{ secrets.SSH_PRIVATE_KEY_BEGIN_END }} 
     #       known_hosts: ${{ secrets.SSH_HOST }}
     #   - name: rsync over ssh
     #     run: rsync ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/

      #${{ secrets.SERVER_IP }}
      #${{ secrets.SERVER_PASSWORD }}
      #${{ secrets.SERVER_USERNAME }}
      #${{ secrets.SSH_HOST }}
      #${{ secrets.SSH_PRIVATE_KEY }}
      #${{ secrets.SSH_PRIVATE_KEY_BEGIN_END }}
      #${{ secrets.SSH_PUBLIC_KEY }}
