#https://github.com/shimataro/ssh-key-action
name: CI
on: [push]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
            key: ${{ secrets.SSH_PRIVATE_KEY_BEGIN_END }} 
            known_hosts: ${{ secrets.SSH_HOST }}
      #- name: rsync
      #  run: rsync ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/
        
      - name: pull via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: cd /var/www/html/Fiscus_bis #sudo git pull

      #${{ secrets.SERVER_IP }}
      #${{ secrets.SERVER_PASSWORD }}
      #${{ secrets.SERVER_USERNAME }}
      #${{ secrets.SSH_HOST }}
      #${{ secrets.SSH_PRIVATE_KEY }}
      #${{ secrets.SSH_PRIVATE_KEY_BEGIN_END }}
      #${{ secrets.SSH_PUBLIC_KEY }}
